# Generated by Django 2.2.26 on 2022-09-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kennel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog', models.ManyToManyField(related_name='dog_dog', to='kennel.Kennel')),
            ],
        ),
    ]
