# Generated by Django 2.2.26 on 2022-09-27 18:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kennel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kennel', models.ManyToManyField(related_name='kennel_kennel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
